development:
  adapter: mysql
  datbase: tvshows_development
  username: root
  password: 

test:
  adapter: mysql
  datbase: tvshows_test
  username: root
  password: 

production:
  adapter: mysql
  datbase: tvshows_production
  username: root
  password: 
