development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tvshows_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tvshows_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tvshows_production
  username: root
  password:
  socket: /tmp/mysql.sock
